workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
    scripts:
      - |
        # set up debug key.properties
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/counter_flutter/.android/local.properties"
      - flutter packages pub get
      - cd $FCI_BUILD_DIR/counter_flutter && flutter test
      - cd $FCI_BUILD_DIR/CourtCounter && ./gradlew assembleDebug
    publishing:
      email:
        recipients:
          - sbis1999@gmail.com
    artifacts:
      - CourtCounter/app/build/**/outputs/**/*.apk
      - flutter_drive.log
